version: '3.9'
name: adguardhome
# AdGuard Home stack

# Page: https://adguard.com/en/adguard-home/overview.html
# Dckr: https://hub.docker.com/r/adguard/adguardhome
# Repo: https://github.com/AdguardTeam/AdGuardHome

# AdGuard Home is a network-wide software for blocking ads & tracking. After
# you set it up, it’ll cover ALL your home devices, and you don’t need any
# client-side software for that. With the rise of Internet-Of-Things and
# connected devices, it becomes more and more important to be able to control
# your whole network.

services:

  app:
    container_name: adguard
    image: adguard/adguardhome
    volumes:
      - /etc/adguard:/opt/adguardhome/conf
      - /srv/adguard:/opt/adguardhome/work
    ports:
      - 53:53 # DNS
      - 67:67/udp # DHCP
      - 68:68 # DHCP
      - 31877:80/tcp # HTTP/DNS-over-HTTP
      - 32201:443 # HTTPS/DNS-over-HTTPS
      - 30512:3000/tcp # Web UI
      - 853:853/tcp # DNS-over-TLS
      - 784:784/udp # DNS-over-QUIC
      - 853:853/udp # DNS-over-QUIC
      - 8853:8853/udp # DNS-over-QUIC
      - 5443:5443 # DNSCrypt
    restart: unless-stopped
    privileged: true
    #network_mode: host
