version: '3.5'
# Jellyfin stack
# Page: https://jellyfin.org/
# Code: https://github.com/jellyfin/jellyfin
# Jellyfin is the volunteer-built media solution that puts you in control of
# your media. Stream to any device from your own server, with no strings
# attached. Your media, your server, your way.

services:
  app:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: 'host'
    volumes:
      - /etc/jellyfin:/config
      - /media/cache:/cache
      - /media/level1:/media
    restart: 'unless-stopped'
    healthcheck:
      test: "curl -f http://localhost:8096/ || exit 1"
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl
    # Optional - may be necessary for docker healthcheck to pass if running in
    #            host network mode
    extra_hosts:
      - "host.docker.internal:host-gateway"