version: '3.9'
# Calckey stack
# Page: https://docker-mailserver.github.io/docker-mailserver/latest/
# Code: https://github.com/docker-mailserver/docker-mailserver
# Production-ready fullstack but simple mail server
# (SMTP, IMAP, LDAP, Antispam, Antivirus, etc.) running inside a container.

services:

  app:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.sowi.tech
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "993:993"
    volumes:
      - data:/var/mail/
      - state:/var/mail-state/
      - logs:/var/log/mail/
      - config:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ENABLE_RSPAMD
      - ENABLE_CLAMAV
      - ENABLE_FAIL2BAN
    cap_add:
      - NET_ADMIN # For Fail2Ban to work
    restart: unless-stopped
  
volumes:
  data:
  state:
  logs:
  config: