version: '3.9'
# Prometheus stack
# Page: https://prometheus.io/
# Code: https://github.com/prometheus
# Prometheus, a Cloud Native Computing Foundation project, is a systems and
# service monitoring system. It collects metrics from configured targets at
# given intervals, evaluates rule expressions, displays the results, and can
# trigger alerts when specified conditions are observed.

services:
  app:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 31089:9090
    restart: unless-stopped
    healthcheck:
      test: "wget -O /dev/null -q http://localhost:9090/-/healthy 2>/dev/null || exit 1"
    volumes:
      - /etc/prometheus:/etc/prometheus
      - data:/prometheus

volumes:
  data: