version: "3.9"
# Uptime Kuma stack
# Page: https://uptime.kuma.pet/
# Code: https://github.com/louislam/uptime-kuma
# Uptime Kuma is an easy-to-use self-hosted monitoring tool.

services:
  app:
    image: louislam/uptime-kuma:alpine
    container_name: uptime-kuma
    restart: unless-stopped
    ports:
      - "30936:3001"
    volumes:
      - data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  data: